name: flutter_news_app_api_server_full_source_code
description: The complete backend API server for the Flutter News App Toolkit, built with Dart Frog. Powers authentication, data management, user settings, and more.
repository: https://github.com/flutter-news-app-full-source-code/flutter-news-app-api-server-full-source-code
publish_to: none
version: 1.2.0

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.2.0
  data_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-client.git
      ref: v1.0.1
  data_mongodb:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-mongodb.git
      ref: v1.0.1
  data_repository:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-repository.git
      ref: v1.0.1
  dotenv: ^4.2.0
  email_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-client.git
      ref: v1.0.1
  email_repository:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-repository.git
      ref: v1.0.1
  email_sendgrid:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-sendgrid.git
      ref: v1.0.1
  equatable: ^2.0.7
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
      ref: v1.0.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  mongo_dart: ^0.10.5
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^9.0.0

dependency_overrides:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 8bae6eb17369b76f72961870a22ee13d3073fa61
  data_mongodb:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-mongodb.git
      ref: cb4848f25a5914ec705cf2c743ec6fc75171f7fa
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
      ref: v1.1.0
