name: flutter_news_app_backend_api_full_source_code
description: The complete backend API for the Flutter News App Toolkit, built with Dart Frog. Powers authentication, data management, user settings, and more.
repository: https://github.com/flutter-news-app-full-source-code/flutter-news-app-api-server-full-source-code
publish_to: none
version: 1.10.0

environment:
  sdk: ^3.9.0

dependencies:
  asn1lib: ^1.6.5
  collection: ^1.19.1
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 22d63162293ec823de36659a7eedd3f91ce1396f
  crypto: ^3.0.7
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.2.0
  dotenv: ^4.2.0
  equatable: ^2.0.7
  intl: ^0.20.2
  jose: ^0.3.3
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  mime: ^1.0.6
  mongo_dart: ^0.10.5
  path: ^1.9.1
  pointycastle: ^4.0.0
  shelf_cors_headers: ^0.1.5
  uuid: ^4.5.3

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_test: ^0.1.2
  json_serializable: ^6.10.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^9.0.0
